version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: budzet
    ports:
      - "3306:3306"
  app:
    build:
      context: '.'
      args:
        host_uid: $HOST_UID
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: 'php bin/console server:run --docroot=./private_html 0.0.0.0:8080'
networks:
  default:
    external:
      name: budzet-rozliczeniowy

