version: '2'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: budzet
    ports:
      - "5432:5432"
    networks:
      - application
  app:
    build:
      context: '.'
      args:
        host_uid: $HOST_UID
    links:
      - db
    ports:
      - "8080:8080"
    networks:
      - application
    volumes:
      - .:/app
    command: 'php bin/console server:run 0.0.0.0:8080'
networks:
  application:

