version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: budzet
    ports:
      - "3306:3306"
    networks:
      - application
#  db:
#    image: postgres:9.6-alpine
#    environment:
#      POSTGRES_PASSWORD: example
#      POSTGRES_DB: budzet
#    ports:
#      - "5432:5432"
#    networks:
#      - application
  app:
    build:
      context: '.'
      args:
        host_uid: $HOST_UID
    links:
      - db
    ports:
      - "8080:8080"
    networks:
      - application
    volumes:
      - .:/app
    command: 'php bin/console server:run --docroot=./private_html 0.0.0.0:8080'
networks:
  application:

