parameters:
  locale: 'api'
  app.tenant_url: https://megawebmaster.eu.auth0.com

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Security\Guard\Auth0Guard:
    arguments: ['%app.tenant_url%']
